# Docker Compose override for development
# This file is automatically loaded by docker-compose and provides
# development-specific configurations like volume mounts and auto-reload

services:
  backend:
    volumes:
      # Mount source code for development hot-reload
      - ./backend:/app/backend
      - ./shared:/app/shared
    environment:
      - FLASK_DEBUG=1
      - MONGO_URI=mongodb://mongodb:27017/listenup-mongo-db
      # Force unbuffered Python output for real-time development logging
      # Production should NOT use this for better performance
      - PYTHONUNBUFFERED=1
    command: ["python", "-m", "flask", "run", "--reload"]

  # Override MongoDB to disable authentication for development
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
      MONGO_INITDB_DATABASE: "listenup-mongo-db"
    
  flucoma_service:
    environment:
      # Force Python to output immediately to Docker logs instead of buffering
      # Without this, print() statements may not appear in logs until the buffer fills
      # ONLY for development - production should use buffered output for performance
      - PYTHONUNBUFFERED=1
    working_dir: /app/microservices/flucoma_service
    # The -u flag also forces unbuffered output (same as PYTHONUNBUFFERED=1)
    # This ensures real-time logging for debugging and monitoring
    command: ["python", "-u", "app.py"]
    volumes:
      # Mount source code for development hot-reload
      - ./microservices/flucoma_service:/app/microservices/flucoma_service
      - ./microservices/shared:/app/microservices/shared
      - ./shared:/app/shared
      
  librosa_service:
    environment:
      # Development-only unbuffered output for real-time logging
      - PYTHONUNBUFFERED=1
    command: ["python", "-u", "app.py"]
    volumes:
      # Mount source code for development hot-reload
      - ./microservices/librosa_service:/app/microservices/librosa_service
      - ./microservices/shared:/app/microservices/shared
      - ./shared:/app/shared
