from enum import Enum

class EventType(str, Enum):
    STATUS_UPDATE = "STATUS_UPDATE"
    FINAL_STATUS = "FINAL_STATUS"
    PROGRESS_UPDATE = "PROGRESS_UPDATE"
    LOG_MESSAGE = "LOG_MESSAGE"
    JOB_SUBMIT = "JOB_SUBMIT"
    JOB_STEP_EXECUTE = "JOB_STEP_EXECUTE"
    JOB_STEP_COMPLETE = "JOB_STEP_COMPLETE"
    JOB_STEP_FAILED = "JOB_STEP_FAILED"

